app_name = "gdp"
master_core = 0
duration = 20

[mempool]
    capacity = 65535
    cache_size = 256

[[ports]]
    name = "eth1"
    device = "0000:00:08.0"
    cores = [0]
    rxd = 512
    txd = 512

[[ports]]
    name = "eth2"
    device = "0000:00:09.0"
    cores = [0]
    rxd = 512
    txd = 512

[[ports]]
    name = "eth3"
    device = "0000:00:0a.0"
    cores = [0]
    rxd = 512
    txd = 512

[[ports]]
    name = "eth4"
    device = "0000:00:10.0"
    cores = [0]
    rxd = 512
    txd = 512

[[ports]]
    name = "loc"
    device = "net_tap0"
    args = "iface=controltap"
    cores = [0]
    rxd = 1024
    txd = 1024
